version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo/db:/mongo/db
    ports:
      - "27017:27017"

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/user/dthought/api
    ports:
      # outer:inner
      - "5000:8080"
    links:
      - mongo
    depends_on:
      - 'mongo'

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend/src:/frontend/src 
    ports:
      - "3000:3000"